### ISSUE TITLE
Broadcast to one component

### ISSUE THREAD

**Issue by tdalianis** [kevoree/kevoree-library#22]
Hi, 

is there a way to have many components 'listening' to the same channel and at the same time be able to send a message only to one of them?

Thanks

**Comment by maxleiko** [comment]
- *"manu components 'listening' to the same channel"*
 - Bind your components input to the channel. This is the standard behavior for channels. They do broadcast to all connected input.  
- *"at the same time [...] send a message to only one"*
 - at the same time ? not sure to follow there.
 - sending a message to only one component if there is multiple component connected is not possible with the current channels.

**Comment by maxleiko** [comment]
If you want a specific type of communication between ports you can always create a specific channel type.

You can have a look at the existing channels in the standard library [here](https://github.com/kevoree/kevoree-library/tree/master/java/org.kevoree.library.java.channels/src/main/java/org/kevoree/library)
