### ISSUE TITLE
kevoree registry

### ISSUE THREAD

**Issue by alliSoftwareAG** [kevoree/kevoree-library#28]
Hi,
I am trying to work with the new registry, but when I give mvn deploy it fails with the following error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project ApamaComponent: Failed to update metadata org.kevoree.project:ApamaComponent:1.0.0-SNAPSHOT/maven-metadata.xml: Could not parse metadata /home/alli/.m2/repository/org/kevoree/project/ApamaComponent/1.0.0-SNAPSHOT/maven-metadata-allisoftwareag.xml: attribute value must start with quotation or apostrophe not n (position: START_DOCUMENT seen ... <html class=n... @1:265) -> [Help 1]

If I have a look at this xml file, I can see, that there is really no quotation or apostrophe at this point:
...  <html class=no-js> ...

I cannot fix this, due to the fact, that every time I give mvn deploy, this file is downloaded new from the registry. 

Can somebody help me with this?

@maxleiko do you have an idea, where the problem is and what I am doing wrong?

Thank you :)

**Comment by skorsky** [comment]
Can you add the corrupt XML file and the pom.xml of the project?

**Comment by alliSoftwareAG** [comment]
I am adding them as .txt, due to the fact, that github is not accepting xml files. Just change the end of the file back to .xml .
[pom.txt](https://github.com/kevoree/kevoree-library/files/690000/pom.txt)
[maven-metadata-allisoftwareag.txt](https://github.com/kevoree/kevoree-library/files/690001/maven-metadata-allisoftwareag.txt)

**Comment by skorsky** [comment]
May be adding a snapshot repository in the distribution management helps:
`
    <distributionManagement>
	<snapshotRepository>
            <id>...</id> 
            <name>...</name> 
            <url>http://...</url> 
        </snapshotRepository>
        
    </distributionManagement>
`

**Comment by maxleiko** [comment]
Why do you want to publish this project to a Maven repository?

Also, the Kevoree registry is Kevoree-related only, it is **not** a Maven repository. So this:
```xml
	<distributionManagement>
		<repository>
			<id>allisoftwareag</id>
			<name>allisoftwareag</name>
			<url>https://registry.kevoree.org/#/ns/allisoftwareag/</url>
		</repository>
	</distributionManagement>
```

Makes no sense.

Maven deployment ([see this](http://maven.apache.org/plugins/maven-deploy-plugin/)) is **not** related to Kevoree publication. Publishing a Kevoree model to the Kevoree registry is just giving that registry an abstraction of your project in `.json`. Deploying an artifact on a Maven repository is publishing your project `.jar` to that repository. Both are separate concerns.

**Comment by maxleiko** [comment]
[More details on Kevoree registry publications](https://github.com/dukeboard/kevoree/wiki/Migrate-to-new-registry-(v5.4.0-SNAPSHOT-and-above))

**Comment by alliSoftwareAG** [comment]
Yes, thank you.
