### ISSUE TITLE
Global model available to client nodes

### ISSUE THREAD

**Issue by tdalianis** [kevoree/kevoree-library#29]
Hi,

It seems that the global model is not available on the client node programmatically. When I try to use modelService.getCurrentModel().getModel() the nodes that i get, are only the master node and the client node and not the rest.

Is there a way to have a list of all the kevoree nodes on a client node?

**Comment by maxleiko** [comment]
Note: this is only happening when using `CentralizedWSGroup`, which is the expected behavior for now.  

=> TODO => add a possibility to disable the reducing feature if needed

**Comment by maxleiko** [comment]
Available in [v2](https://registry.kevoree.org/#/tdefs/1553)
