### ISSUE TITLE
mvn clean install fails

### ISSUE THREAD

**Issue by tdalianis** [kevoree/kevoree-library#30]
For some reason mvn clean install fails when repository (or kevoree folder) is empty

Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar (165 KB at 284.8 KB/sec)
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.kevoree.tools:org.kevoree.tools.mavenplugin:5.4.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.kevoree.tools:org.kevoree.tools.mavenplugin:jar:5.4.0-SNAPSHOT in snap (http://oss.sonatype.org/content/groups/public/) @
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project gr.atc.heads:atcHeadsCollectors:1.0.0-SNAPSHOT (C:\Users\TDalianis\workspace_heads\atcHeadsCollectors\pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin org.kevoree.tools:org.kevoree.tools.mavenplugin:5.4.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.kevoree.tools:org.kevoree.tools.mavenplugin:jar:5.4.0-SNAPSHOT in snap (http://oss.sonatype.org/content/groups/public/) -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException

**Comment by maxleiko** [comment]
I've released Kevoree `5.4.0` two weeks ago. You should use this version for Kevoree instead of the SNAPSHOT.  
For the error, I think it's your .m2 that is corrupted or your pom file. Can't tell with just the error log.

**Comment by tdalianis** [comment]
emm I know but you had told me then not to switch to the new version yet :)
I had tried it with an empty .m2, it wasn't that, changing the .pom to the new version instead of the SNAPSHOT did the trick :)
